#!/usr/bin/env python3
"""Initialize Phase 3 (paradigm v3, feature-semantic) from a controller work
order and a frozen Phase 2 feature map.

v3 是唯一主流程（旧 main_gmi / legacy work-order 消费链已按 #50 删除）：
- 输入：feature-map.json surfaces[] + navigation-relations.candidates.csv +
  data-relations.csv（数据层 interface-only 契约）；
- 骨架规则：page → 路由节点+页面壳；sheet/dialog/menu → 挂载宿主页的
  模态载体（不独立路由）；container/reusable-component → 不生成壳；
- 门禁前置：gmi 冻结 phase-2-closure.json gate 直读 + 工单链校验。
"""

from __future__ import annotations

import argparse
import colorsys
import csv
import hashlib
import json
import shutil
import tempfile
import re
from pathlib import Path
from typing import Any

import data_contracts
from _common import (
    atomic_json,
    atomic_text,
    csv_fieldnames,
    load_json,
    read_csv,
    sha256_file,
    sha256_text,
    utc_now,
    validate_id,
    write_csv,
)


SKILL_ROOT = Path(__file__).resolve().parents[1]
ASSETS = SKILL_ROOT / "assets"
ARKUI_TEMPLATE = ASSETS / "arkui-stage-template"
PHASE_NAME = "phase-03-harmony-scaffold"
PHASE3_ROLES = (
    "architecture_lead_id",
    "toolchain_agent_id",
    "navigation_agent_id",
    "public_ui_agent_id",
    "capability_contract_agent_id",
    "architecture_acceptance_agent_id",
)
ASSET_INVENTORY_FIELDS = [
    "asset_id", "source_path", "archive_path", "sha256", "asset_type",
    "feature_ids", "page_ids", "state_ids", "created_by", "created_at",
    "reviewed_by", "reviewed_at", "status", "notes",
]
SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
PAGE_SHELL_DIR = "entry/src/main/ets/pages/shells"
TEMPLATE_EXCLUDES = {
    ".git", ".idea", ".hvigor", "oh_modules", "node_modules", "build", "dist",
    ".preview", "local.properties", "oh-package-lock.json5", ".DS_Store",
}
TEMPLATE_REQUIRED = {
    "AppScope/app.json5", "build-profile.json5", "oh-package.json5",
    "entry/build-profile.json5", "entry/src/main/module.json5",
    "entry/src/main/ets/entryability/EntryAbility.ets",
    "entry/src/main/ets/pages/Index.ets",
}






def requirement_id(feature_id: str, source_kind: str, source_ref: str) -> str:
    digest = sha256_text(f"{feature_id}|{source_kind}|{source_ref}")[:20].upper()
    return f"HREQ-{digest}"


def copy_template_csv(temp_dir: Path, source_name: str, target_name: str) -> None:
    shutil.copyfile(ASSETS / source_name, temp_dir / target_name)


def semantic_csv_rows(path: Path, label: str) -> list[dict[str, str]]:
    """2.1 语义输入候选表读取（存在才消费，缺失时由调用方回退现状）。"""
    try:
        with path.open("r", encoding="utf-8-sig", newline="") as handle:
            return list(csv.DictReader(handle))
    except OSError as exc:
        raise ValueError(f"Cannot read {label}: {exc}") from exc


def page_shell_symbol(page_id: str) -> str:
    """从 Page-ID 确定性派生页面壳 ArkTS struct 名（无随机性，可重放）。"""
    parts = page_id.split("-")
    if parts and parts[0] == "PAGE":
        parts = parts[1:]
    name = "".join(part.capitalize() for part in parts if part)
    return f"ShellPage{name}"


def render_page_shell(page_id: str, shell_symbol: str, feature_ids: list[str]) -> str:
    """生成确定性页面壳种子：空白内容区 + 身份字面量，无业务逻辑。"""
    feature_literal = ";".join(feature_ids) if feature_ids else "NONE"
    return (
        "// Deterministic Phase 3 page-shell seed generated by init_scaffold from\n"
        "// P2 navigation-relations (+ behavior-contracts). Pure shell, no business\n"
        "// logic; the navigation agent finalizes registration and identity literals.\n"
        f"// Feature-ID: {feature_literal}\n"
        "\n"
        "@Component\n"
        f"export struct {shell_symbol} {{\n"
        "  build() {\n"
        "    NavDestination() {\n"
        "      Column() {}\n"
        "        .width('100%')\n"
        "        .height('100%')\n"
        f"        .id('{page_id}')\n"
        "    }\n"
        f"    .title('{page_id}')\n"
        f"    .id('{shell_symbol}')\n"
        "  }\n"
        "}\n"
    )


def modal_shell_symbol(surface_id: str) -> str:
    """从 Surface-ID 确定性派生模态载体 ArkTS struct 名（与页面壳同派生规则）。"""
    return page_shell_symbol(surface_id).replace("ShellPage", "ShellModal", 1)


def render_modal_shell(
    surface_id: str, shell_symbol: str, kind: str, host_surface_id: str | None
) -> str:
    """生成确定性模态载体种子（sheet/dialog/menu）：不独立路由，挂载宿主页。

    纯载体壳：空白内容区 + 身份字面量 + 宿主挂载声明，无业务逻辑；
    Phase 4 的实现代理负责在宿主页接线（bindSheet/CustomDialog 等）。
    """
    host_literal = host_surface_id or "UNRESOLVED"
    return (
        "// Deterministic Phase 3 modal-carrier seed generated by init_scaffold\n"
        "// (paradigm v3) from P2 feature-map surfaces. sheet/dialog/menu surfaces\n"
        "// are NOT independent routes: they mount on the host page below. Pure\n"
        "// carrier shell, no business logic; the implementation agent wires the\n"
        "// host-side mount (bindSheet / CustomDialog / menu anchor).\n"
        f"// Surface-Kind: {kind}\n"
        f"// Mount-Host: {host_literal}\n"
        "\n"
        "@Component\n"
        f"export struct {shell_symbol} {{\n"
        "  build() {\n"
        "    Column() {}\n"
        "      .width('100%')\n"
        "      .height('100%')\n"
        f"      .id('{surface_id}')\n"
        "  }\n"
        "}\n"
    )




def template_files(root: Path) -> list[Path]:
    if not root.is_dir() or root.is_symlink():
        raise ValueError(f"ArkUI Stage template is missing or unsafe: {root}")
    result: list[Path] = []
    for path in sorted(root.rglob("*")):
        relative = path.relative_to(root)
        if any(part in TEMPLATE_EXCLUDES for part in relative.parts):
            continue
        if path.is_symlink():
            raise ValueError(f"Symbolic links are prohibited in the ArkUI template: {path}")
        if path.is_file():
            result.append(path)
    names = {path.relative_to(root).as_posix() for path in result}
    missing = TEMPLATE_REQUIRED - names
    if missing:
        raise ValueError(f"ArkUI Stage template lacks required files: {sorted(missing)}")
    return result


def template_manifest(root: Path) -> str:
    return "".join(
        f"{sha256_file(path)}  {path.relative_to(root).as_posix()}\n"
        for path in template_files(root)
    )


def create_arkui_project(template: Path, destination: Path, replacements: dict[str, str]) -> dict[str, Any]:
    destination.mkdir()
    files = template_files(template)
    text_suffixes = {".json", ".json5", ".ets", ".ts", ".txt", ".md", ".csv"}
    for source in files:
        relative = source.relative_to(template)
        target = destination / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        if source.suffix.lower() in text_suffixes or source.name == ".gitignore":
            text = source.read_text(encoding="utf-8")
            for token, value in replacements.items():
                text = text.replace(token, value)
            with target.open("w", encoding="utf-8", newline="\n") as handle:
                handle.write(text)
        else:
            shutil.copyfile(source, target)
    unresolved = []
    for path in destination.rglob("*"):
        if path.is_file() and (path.suffix.lower() in text_suffixes or path.name == ".gitignore"):
            if re.search(r"__[A-Z0-9_]+__", path.read_text(encoding="utf-8")):
                unresolved.append(path.relative_to(destination).as_posix())
    if unresolved:
        raise ValueError(f"Unresolved ArkUI template tokens remain: {unresolved}")
    generated = "".join(
        f"{sha256_file(path)}  {path.relative_to(destination).as_posix()}\n"
        for path in sorted(destination.rglob("*")) if path.is_file()
    )
    return {
        "schema_version": 1,
        "template_id": "ARKUI-STAGE-TEMPLATE-V1",
        "template_manifest_sha256": hashlib.sha256(template_manifest(template).encode("utf-8")).hexdigest(),
        "generated_file_count": len(files),
        "generated_project_manifest_sha256": hashlib.sha256(generated.encode("utf-8")).hexdigest(),
        "required_files": sorted(TEMPLATE_REQUIRED),
        "bundle_name": replacements["__BUNDLE_NAME__"],
        "app_name": replacements["__APP_NAME__"],
        "vendor": replacements["__VENDOR__"],
        "log_tag": replacements["__LOG_TAG__"],
    }


def canonical_input(value: str, label: str) -> Path:
    raw = Path(value).expanduser().absolute()
    if raw.is_symlink():
        raise ValueError(f"{label} must not be a symbolic link: {raw}")
    return raw.resolve()


def require_object(value: Any, label: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ValueError(f"{label} must be a JSON object")
    return value


def validate_phase3_ownership(work_order: dict[str, Any], scope: dict[str, Any]) -> dict[str, str]:
    ownership = require_object(work_order.get("ownership"), "Phase 3 work-order ownership")
    normalized: dict[str, str] = {}
    for role in PHASE3_ROLES:
        actor = ownership.get(role)
        if not isinstance(actor, str) or not actor.strip():
            raise ValueError(f"Phase 3 work order is missing ownership.{role}")
        normalized[role] = actor.strip()
    if len(set(normalized.values())) != len(PHASE3_ROLES):
        raise ValueError("All six frozen Phase 3 role IDs must be distinct")
    previous = scope.get("ownership") if isinstance(scope.get("ownership"), dict) else {}
    previous_ids = {
        actor
        for value in previous.values()
        for actor in (value if isinstance(value, list) else [value])
        if isinstance(actor, str) and actor
    }
    overlap = sorted(set(normalized.values()) & previous_ids)
    if overlap:
        raise ValueError(f"Phase 3 roles must be independent from frozen Phase 1/2 roles: {overlap}")
    return normalized






def input_record(
    source: Path,
    snapshot: Path | None = None,
    *,
    use_snapshot_as_path: bool = False,
) -> dict[str, Any]:
    # #48 裁定：path/snapshot_path/source_path 全部输出绝对规范路径
    # （str(path.resolve())），与 Gate 3 的 canonical 校验口径一致。
    record: dict[str, Any] = {
        "path": str(
            (snapshot if use_snapshot_as_path and snapshot is not None else source).resolve()
        ),
        "sha256": sha256_file(source),
    }
    if snapshot is not None:
        record["snapshot_path"] = str(snapshot.resolve())
    if use_snapshot_as_path:
        record["source_path"] = str(source.resolve())
    return record










# ---------------------------------------------------------------------------
# Paradigm v3（feature-semantic）：feature-map 驱动的功能承载面骨架。
#
# 设计输入：feature-map.json surfaces[]（去重 UI 承载面，kind 分类）+
# candidates/navigation-relations.candidates.csv（跳转图参考）+
# data-relations.csv（数据层语义契约）。
#
# 骨架规则：page → 路由节点+页面壳；sheet/dialog/menu → 挂载宿主页的
# 模态载体（不独立路由）；container/reusable-component → 不生成壳
# （透明宿主/复用组件，其 content surface 才生成——容器死锁根治）。
#
# 退役（本范式不消费）：旧契约布局 ~8 文件（closure-report.json/CLOSED/
# acceptance-registry.csv/evidence-anchors.snapshot.csv/四方一致性）、
# inventory.csv 26 列页面行、audit-replay/evidence-index。
# 保留：gmi 冻结闭包门禁（phase-2-closure.json gate 直读）、Phase 3 工单
# 链、input-lock、ArkUI 模板机制、asset 哈希链、环境冻结（freeze_env）。
# ---------------------------------------------------------------------------

V3_PARADIGM = "feature-semantic"
V3_SURFACE_KINDS = frozenset({"page", "container", "sheet", "dialog", "menu", "reusable-component"})
V3_MODAL_KINDS = frozenset({"sheet", "dialog", "menu"})
V3_MODAL_SHELL_DIR = "entry/src/main/ets/pages/modals"
V3_RETIREMENT_NOTE = (
    "paradigm v3 retired inputs: closure-report.json/CLOSED/acceptance-registry.csv/"
    "evidence-anchors.snapshot.csv four-way chain, inventory.csv 26-column page rows, "
    "audit-replay/evidence-index consumption"
)


def load_feature_map(path: Path) -> dict[str, Any]:
    """读取并校验 feature-map.json（v3 必需输入，Phase 2 权威 schema）。"""
    data = require_object(load_json(path), "feature-map.json")
    if data.get("schema_version") != 1:
        raise ValueError("feature-map.json schema_version must be 1")
    features = data.get("features")
    if not isinstance(features, list) or not features:
        raise ValueError("feature-map.json features must be a non-empty array")
    coverage = require_object(data.get("coverage_gate"), "feature-map coverage_gate")
    if coverage.get("included_features_covered") is not True:
        raise ValueError("feature-map coverage_gate is not covered")
    seen_features: set[str] = set()
    seen_surfaces: set[str] = set()
    normalized: list[dict[str, Any]] = []
    for feature in features:
        if not isinstance(feature, dict):
            raise ValueError("feature-map features[] entries must be objects")
        feature_id = str(feature.get("feature_id", "")).strip()
        validate_id(feature_id, "Feature-ID in feature-map")
        if feature_id in seen_features:
            raise ValueError(f"Duplicate feature-map Feature-ID: {feature_id}")
        seen_features.add(feature_id)
        surfaces: list[dict[str, Any]] = []
        for surface in feature.get("surfaces") or []:
            if not isinstance(surface, dict):
                raise ValueError(f"{feature_id}: surfaces[] entries must be objects")
            surface_id = str(surface.get("id", "")).strip()
            validate_id(surface_id, "Surface-ID in feature-map")
            if surface_id in seen_surfaces:
                # GD-P3-05: a behavior-host entry is a reference to an already
                # declared surface (component features delegate their carrier
                # to the host page); duplicates are rejected otherwise.
                if str(surface.get("relation", "")).strip() != "behavior-host":
                    raise ValueError(f"Duplicate feature-map Surface-ID: {surface_id}")
                continue
            seen_surfaces.add(surface_id)
            kind = str(surface.get("kind", "")).strip()
            if kind not in V3_SURFACE_KINDS:
                raise ValueError(f"{surface_id}: unknown surface kind {kind!r}")
            is_container = surface.get("is_container") is True
            if is_container != (kind == "container"):
                raise ValueError(f"{surface_id}: is_container must agree with kind=='container'")
            surfaces.append({"id": surface_id, "kind": kind, "is_container": is_container})
        normalized.append({"feature_id": feature_id, "surfaces": surfaces})
    included = [str(item) for item in coverage.get("included", [])]
    if sorted(included) != sorted(seen_features):
        raise ValueError("feature-map coverage_gate.included differs from features[] ids")
    return {
        "feature_count": len(normalized),
        "surface_count": sum(len(f["surfaces"]) for f in normalized),
        "included": included,
        "features": normalized,
    }


def build_surface_plan(
    feature_map: dict[str, Any],
    navigation_relations: list[dict[str, str]],
) -> dict[str, Any]:
    """feature-map surfaces → 确定性骨架计划（route / modal@host / none）。

    page → 路由节点+页面壳；sheet/dialog/menu → 模态载体，宿主三层确定性
    推断（不发明拓扑，来源全部记录在 mount_host_source）：
      1. nav-explicit-edge：跳转边 to==modal surface 且 from==page surface；
      2. feature-page：同 feature 恰有一个 page surface；
      3. fallback-sorted-first-route：排序后首个路由面（无路由面则 unresolved）。
    container/reusable-component → passthrough（不生成壳，Phase 4 透明宿主）。
    跳转边仅当两端都精确命中 surface 清单才保留（真实 run 中 nav 表页面
    哈希与 feature-map 不同轮次，交集可能为 0——如实保留计数，不报错）。
    """
    surfaces: list[dict[str, Any]] = []
    seen_surface_ids: set[str] = set()
    for feature in feature_map["features"]:
        for surface in feature["surfaces"]:
            # GD-P3-05: one shell per surface (first declaration wins). A
            # behavior-host entry references an existing surface and must not
            # duplicate the shell plan or the input-lock surfaces array.
            if surface["id"] in seen_surface_ids:
                continue
            seen_surface_ids.add(surface["id"])
            surfaces.append({**surface, "feature_id": feature["feature_id"]})
    by_id = {surface["id"]: surface for surface in surfaces}
    route_rows = sorted(
        (s for s in surfaces if s["kind"] == "page"), key=lambda s: s["id"]
    )
    route_ids = {s["id"] for s in route_rows}
    modal_ids = {s["id"] for s in surfaces if s["kind"] in V3_MODAL_KINDS}

    host_edges: dict[str, set[str]] = {}
    kept_edges: list[dict[str, str]] = []
    skipped_nav_pages: set[str] = set()
    nav_pages: set[str] = set()
    for row in navigation_relations:
        from_id = str(row.get("from_page_id", "")).strip()
        to_id = str(row.get("to_page_id", "")).strip()
        for page_id in (from_id, to_id):
            if page_id:
                nav_pages.add(page_id)
        if from_id in by_id and to_id in by_id:
            kept_edges.append(
                {
                    "candidate_id": str(row.get("candidate_id", "")).strip(),
                    "from_surface_id": from_id,
                    "to_surface_id": to_id,
                    "from_kind": by_id[from_id]["kind"],
                    "to_kind": by_id[to_id]["kind"],
                    "relation_type": str(row.get("relation_type", "")).strip(),
                    "source_ref": str(row.get("source_ref", "")).strip(),
                }
            )
            if to_id in modal_ids and from_id in route_ids:
                host_edges.setdefault(to_id, set()).add(from_id)
    skipped_nav_pages = nav_pages - set(by_id)

    feature_pages: dict[str, list[str]] = {}
    for surface in route_rows:
        feature_pages.setdefault(surface["feature_id"], []).append(surface["id"])

    routes: list[dict[str, Any]] = []
    modals: list[dict[str, Any]] = []
    passthrough: list[dict[str, Any]] = []
    for surface in sorted(surfaces, key=lambda s: s["id"]):
        surface_id = surface["id"]
        kind = surface["kind"]
        if kind == "page":
            symbol = page_shell_symbol(surface_id)
            routes.append(
                {
                    "surface_id": surface_id,
                    "feature_id": surface["feature_id"],
                    "kind": kind,
                    "route_id": surface_id,
                    "shell_symbol": symbol,
                    "shell_file": f"{PAGE_SHELL_DIR}/{symbol}.ets",
                }
            )
        elif kind in V3_MODAL_KINDS:
            symbol = modal_shell_symbol(surface_id)
            candidates = sorted(host_edges.get(surface_id, set()))
            if candidates:
                host, host_source = candidates[0], "nav-explicit-edge"
                host_candidates = candidates
            elif len(feature_pages.get(surface["feature_id"], [])) == 1:
                host = feature_pages[surface["feature_id"]][0]
                host_source, host_candidates = "feature-page", [host]
            elif route_ids:
                host = sorted(route_ids)[0]
                host_source, host_candidates = "fallback-sorted-first-route", [host]
            else:
                host, host_source, host_candidates = None, "unresolved-no-route-surface", []
            modals.append(
                {
                    "surface_id": surface_id,
                    "feature_id": surface["feature_id"],
                    "kind": kind,
                    "shell_symbol": symbol,
                    "shell_file": f"{V3_MODAL_SHELL_DIR}/{symbol}.ets",
                    "host_surface_id": host,
                    "mount_host_source": host_source,
                    "host_candidates": host_candidates,
                }
            )
        else:
            passthrough.append(
                {
                    "surface_id": surface_id,
                    "feature_id": surface["feature_id"],
                    "kind": kind,
                    "reason": (
                        "transparent-container-host" if kind == "container"
                        else f"no-shell-kind:{kind}"
                    ),
                }
            )
    return {
        "schema_version": 1,
        "paradigm": V3_PARADIGM,
        "routes": routes,
        "modals": modals,
        "passthrough": passthrough,
        "edges": sorted(
            kept_edges,
            key=lambda e: (e["from_surface_id"], e["to_surface_id"], e["candidate_id"]),
        ),
        "skipped_nav_pages": sorted(skipped_nav_pages),
        "stats": {
            "surface_count": len(surfaces),
            "route_count": len(routes),
            "modal_count": len(modals),
            "passthrough_count": len(passthrough),
            "nav_row_count": len(navigation_relations),
            "nav_edge_kept": len(kept_edges),
            "nav_pages_skipped": len(skipped_nav_pages),
        },
    }


def surface_lock_entries(plan: dict[str, Any]) -> list[dict[str, Any]]:
    """骨架计划 → input-lock v3 的 surfaces[]（含 route_or_mount 三态值）。"""
    entries: list[dict[str, Any]] = []
    for route in plan["routes"]:
        entries.append(
            {
                "id": route["surface_id"], "kind": route["kind"], "is_container": False,
                "route_or_mount": "route", "feature_id": route["feature_id"],
                "shell_symbol": route["shell_symbol"], "shell_file": route["shell_file"],
                "mount_host_source": None,
            }
        )
    for modal in plan["modals"]:
        host = modal["host_surface_id"]
        entries.append(
            {
                "id": modal["surface_id"], "kind": modal["kind"], "is_container": False,
                "route_or_mount": f"modal@{host}" if host else "modal@UNRESOLVED",
                "feature_id": modal["feature_id"],
                "shell_symbol": modal["shell_symbol"], "shell_file": modal["shell_file"],
                "mount_host_source": modal["mount_host_source"],
            }
        )
    for item in plan["passthrough"]:
        entries.append(
            {
                "id": item["surface_id"], "kind": item["kind"],
                "is_container": item["kind"] == "container",
                "route_or_mount": "none", "feature_id": item["feature_id"],
                "shell_symbol": None, "shell_file": None,
                "mount_host_source": None,
            }
        )
    return sorted(entries, key=lambda entry: entry["id"])


# ---------------------------------------------------------------------------
# UI 蓝图层（收敛式重构批次 3 #86）：surface-plan 的 UI 原生化决策。
#
# P3 重点不是做更多壳，而是解决"UI 原生化不好"——在 scaffold 阶段就把
# Android UI 在 HarmonyOS 上的表达方式决定下来（native_carrier /
# native_component / preserve / custom_allowed），不让 Phase 4 临时发挥。
#
# 数据来源：Phase 2 visual-memory.json 的 surfaces[].ui_tree_summary
# （class_sequence/class_histogram 可识别 ComposeView/BottomNavigation 等；
# content_descs 携带 Tab/FAB 特征）+ global_palette（主色板）。
# 政策：UI_FIDELITY=HIGH 的机械表达 = preserve 段逐项列出必须保留的
# 文本/入口/状态/色板；custom_allowed 默认 no，仅系统组件确实无法表达
# （自绘类 SurfaceView/TextureView/GLSurfaceView）才 yes 并登记 reason。
# ---------------------------------------------------------------------------

# content_descs 命中 >= TAB_HINT_MIN_HITS 个 → 底栏 Tabs 特征。
TAB_HINT_DESCRIPTORS = frozenset({
    "待办事项", "日历视图", "进展", "待办", "日历", "任务", "日程",
    "首页", "消息", "我的", "设置", "收藏",
})
TAB_HINT_MIN_HITS = 3
# class_histogram 中可识别的底栏导航容器类（子串匹配）。
TAB_NAVIGATION_CLASSES = ("BottomNavigationView", "TabLayout", "NavigationBarView", "BottomBar")
# 自绘/特效宿主类 → custom_allowed=yes 的唯一机械通道。
CUSTOM_DRAW_CLASSES = ("SurfaceView", "TextureView", "GLSurfaceView")
# FAB 特征（content_descs 子串命中，进 android_structure 描述与 preserve）。
FAB_HINT_DESCRIPTORS = ("添加新", "新建", "添加")
# preserve 段采样上限（防超长随机串/噪声撑爆契约）。
PRESERVE_MAX_TEXTS = 12
PRESERVE_MAX_DESCS = 10
PRESERVE_MAX_PALETTE = 4
PRESERVE_TEXT_MAX_LEN = 24

# 映射规则表（kind × 特征 → native_component）的规则名（登记进每项
# matched_rule，供人工审计追溯判定路径）。
RULE_PAGE_TABS = "page+bottom-tabs"
RULE_PAGE_PLAIN = "page+plain-content"
RULE_SHEET = "sheet"
RULE_DIALOG = "dialog"
RULE_MENU = "menu"
RULE_PASSTHROUGH = "container/component-passthrough"


# 主入口页命名标记（Android 主 Activity 命名惯例：Home/Main/Launcher；
# 用于多 page 共享同一快照证据时仲裁底栏 Tabs 唯一持有者）。
PRIMARY_PAGE_MARKERS = ("HOME", "MAIN", "LAUNCHER")


def _tab_bar_signature(
    android_structure_hints: dict[str, Any],
) -> tuple[str | None, int]:
    """底栏导航特征检测：class_histogram 导航容器类优先，次选
    content_descs 命中 TAB_HINT_DESCRIPTORS >= 3。

    返回 (命中证据描述 | None, 强度)。强度用于 plan 级唯一持有者仲裁：
    导航容器类命中 = 999（结构证据最强）；词命中 = 命中词数。纯函数无 IO。
    """
    histogram = android_structure_hints.get("class_histogram")
    if isinstance(histogram, dict):
        for cls in histogram:
            if any(nav in str(cls) for nav in TAB_NAVIGATION_CLASSES):
                return f"class_histogram:{cls}", 999
    descs = android_structure_hints.get("content_descs")
    if isinstance(descs, list):
        hits = sorted(
            {str(d) for d in descs if str(d) in TAB_HINT_DESCRIPTORS}
        )
        if len(hits) >= TAB_HINT_MIN_HITS:
            return "content_descs:" + "+".join(hits), len(hits)
    return None, 0


def map_native_component(kind: str, android_structure_hints: dict[str, Any] | None) -> str:
    """映射规则表（纯函数，可单测）：kind × Android 结构特征 → HarmonyOS
    原生组件组合。

    - page + 底栏导航特征 → Navigation+NavPathStack+Tabs(barPosition=End)
      +List+LazyForEach（三 Tab 主页形态）
    - page + 普通内容    → Navigation+NavPathStack+List/Scroll
    - sheet              → bindSheet(detents MEDIUM/LARGE)
    - dialog             → CustomDialog/bindMenu
    - menu               → bindMenu
    - container/component → none (透传)（Phase 4 透明宿主）
    """
    hints = android_structure_hints if isinstance(android_structure_hints, dict) else {}
    if kind == "page":
        signature, _strength = _tab_bar_signature(hints)
        if signature is not None:
            return "Navigation+NavPathStack+Tabs(barPosition=End)+List+LazyForEach"
        return "Navigation+NavPathStack+List/Scroll"
    if kind == "sheet":
        return "bindSheet(detents MEDIUM/LARGE)"
    if kind == "dialog":
        return "CustomDialog/bindMenu"
    if kind == "menu":
        return "bindMenu"
    return "none (透传)"


def _matched_rule(kind: str, hints: dict[str, Any]) -> str:
    if kind == "page":
        signature, _strength = _tab_bar_signature(hints)
        return RULE_PAGE_TABS if signature is not None else RULE_PAGE_PLAIN
    if kind in V3_MODAL_KINDS:
        return {"sheet": RULE_SHEET, "dialog": RULE_DIALOG, "menu": RULE_MENU}[kind]
    return RULE_PASSTHROUGH


def _android_structure_sentence(surface_id: str, ui_tree_summary: dict[str, Any] | None) -> str:
    """ui_tree_summary → 一句话 Android 主要视觉结构描述（确定性）。"""
    if not isinstance(ui_tree_summary, dict) or not ui_tree_summary:
        return (
            "visual-memory 未覆盖该 surface 的 ui_tree_summary"
            "（Phase 2 无对应运行时快照），结构描述退化"
        )
    parts: list[str] = []
    histogram = ui_tree_summary.get("class_histogram")
    if isinstance(histogram, dict) and histogram:
        ranked = sorted(histogram.items(), key=lambda kv: (-kv[1], kv[0]))
        head = "、".join(
            f"{cls}×{count}" if count > 1 else cls for cls, count in ranked[:4]
        )
        parts.append(f"主要类：{head}")
    if any("ComposeView" in str(cls) for cls in (histogram or {})):
        parts.append("ComposeView 宿主")
    node_count = ui_tree_summary.get("node_count")
    depth = ui_tree_summary.get("depth_max")
    if isinstance(node_count, int) and isinstance(depth, int):
        parts.append(f"{node_count} 节点/最大深度 {depth}")
    descs = ui_tree_summary.get("content_descs")
    if isinstance(descs, list):
        fab = next(
            (d for d in descs if any(hint in str(d) for hint in FAB_HINT_DESCRIPTORS)),
            None,
        )
        if fab is not None:
            parts.append(f"FAB（{fab}）")
    return f"{surface_id}：" + "；".join(parts) if parts else f"{surface_id}：结构摘要为空"


def _preserve_contract(
    ui_tree_summary: dict[str, Any] | None, global_palette: dict[str, Any] | None
) -> dict[str, Any]:
    """UI_FIDELITY=HIGH 的机械表达：必须保留的文本/入口/状态/色板清单。

    从 visual-memory 的 visible_texts（状态/文案）+ content_descs（操作
    入口）+ global_palette（主配色）确定性采样；来源不可用时清单为空但
    note 说明退化（policy 字段保持恒非空）。
    """
    texts: list[str] = []
    descs: list[str] = []
    summary = ui_tree_summary if isinstance(ui_tree_summary, dict) else {}
    for text in summary.get("visible_texts") or []:
        text = str(text).strip()
        if text and len(text) <= PRESERVE_TEXT_MAX_LEN and text not in texts:
            texts.append(text)
        if len(texts) >= PRESERVE_MAX_TEXTS:
            break
    for desc in summary.get("content_descs") or []:
        desc = str(desc).strip()
        if desc and desc != "无" and desc not in descs:
            descs.append(desc)
        if len(descs) >= PRESERVE_MAX_DESCS:
            break
    palette: list[dict[str, str]] = []
    if isinstance(global_palette, dict):
        for group in ("background_colors", "theme_colors"):
            for swatch in global_palette.get(group) or []:
                if isinstance(swatch, dict) and swatch.get("name") and swatch.get("hex"):
                    palette.append(
                        {"name": str(swatch["name"]), "hex": str(swatch["hex"])}
                    )
                if len(palette) >= PRESERVE_MAX_PALETTE:
                    break
            if len(palette) >= PRESERVE_MAX_PALETTE:
                break
    available = bool(texts or descs or palette)
    return {
        "policy": "UI_FIDELITY=HIGH",
        "texts": texts,
        "content_descs": descs,
        "palette": palette,
        "note": (
            "原生重表达必须保留以上可见文本/无障碍入口/主色板"
            if available
            else "visual-memory 对该 surface 无可用证据（无快照或无色板），"
                 "保留要求退化为 feature-map surface 声明本身"
        ),
    }


def _native_carrier_note(route_or_mount: str) -> str:
    """route_or_mount 三态 → 人类可读的 HarmonyOS 承载说明。"""
    if route_or_mount == "route":
        return "route：Navigation 路由节点（独立页面，NavDestination 承载）"
    if route_or_mount.startswith("modal@"):
        host = route_or_mount.split("@", 1)[1]
        return (
            f"modal@{host}：以 bindSheet/CustomDialog 模态挂载于宿主页面 {host}"
        )
    return "none：透传（不生成壳，Phase 4 透明宿主组合进宿主页面）"


def _visual_memory_surface_index(
    visual_memory: dict[str, Any] | None,
) -> dict[str, dict[str, Any]]:
    """visual-memory.surfaces → {surface_id: ui_tree_summary}（缺失退化为空）。"""
    index: dict[str, dict[str, Any]] = {}
    if isinstance(visual_memory, dict):
        for surface in visual_memory.get("surfaces") or []:
            if isinstance(surface, dict) and surface.get("surface_id"):
                index[str(surface["surface_id"])] = (
                    surface.get("ui_tree_summary")
                    if isinstance(surface.get("ui_tree_summary"), dict)
                    else {}
                )
    return index


def _elect_tabs_owner(
    routes: list[dict[str, Any]],
    surface_index: dict[str, dict[str, Any]],
    edges: list[dict[str, Any]],
) -> tuple[str | None, list[str]]:
    """底栏 Tabs 唯一持有者仲裁（一个 Navigation 体系只有一个底栏 Tabs）。

    背景：Phase 2 的 BC after 快照可能让多个 page 共享同一份主页状态
    证据（如 DETAILSCREEN 与 HOMESCREEN 的 content_descs 相同），词特征
    同时命中。机械仲裁（确定性，从强到弱）：
      1. 特征强度（导航容器类 > 更多词命中）；
      2. surface_id 含主入口标记（HOME/MAIN/LAUNCHER，Android 主
         Activity 命名惯例）；
      3. nav 边出度大者（导航源头）；
      4. 字典序最小。
    返回 (owner_surface_id | None, 全部命中特征的 page id 列表)。
    """
    scored: list[tuple[int, str]] = []
    for route in routes:
        summary = surface_index.get(route["surface_id"]) or {}
        hints = {
            "class_histogram": summary.get("class_histogram"),
            "content_descs": summary.get("content_descs"),
        }
        _signature, strength = _tab_bar_signature(hints)
        if strength > 0:
            scored.append((strength, route["surface_id"]))
    if not scored:
        return None, []
    detected = sorted(sid for _s, sid in scored)
    out_degree: dict[str, int] = {}
    for edge in edges:
        out_degree[str(edge.get("from_surface_id", ""))] = (
            out_degree.get(str(edge.get("from_surface_id", "")), 0) + 1
        )

    def _rank(item: tuple[int, str]) -> tuple[int, int, int, str]:
        strength, surface_id = item
        marker = any(m in surface_id.upper() for m in PRIMARY_PAGE_MARKERS)
        return (-strength, 0 if marker else 1, -out_degree.get(surface_id, 0), surface_id)

    owner = min(scored, key=_rank)[1]
    return owner, detected


def attach_ui_blueprint(
    plan: dict[str, Any],
    visual_memory: dict[str, Any] | None,
    visual_memory_source: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """surface-plan 三段（routes/modals/passthrough）原地追加 UI 蓝图字段。

    每 surface 平铺六字段：android_structure / preserve / native_carrier /
    native_component / custom_allowed / reason（+matched_rule 审计追溯）。
    返回顶层 ui_blueprint 摘要（由调用方写入 plan["ui_blueprint"]）。
    """
    surface_index = _visual_memory_surface_index(visual_memory)
    global_palette = (
        visual_memory.get("global_palette")
        if isinstance(visual_memory, dict)
           and isinstance(visual_memory.get("global_palette"), dict)
        else None
    )
    covered = 0
    blueprinted = 0
    tabs_owner, tab_feature_pages = _elect_tabs_owner(
        plan.get("routes", []), surface_index, plan.get("edges", [])
    )

    def _annotate(item: dict[str, Any], route_or_mount: str) -> None:
        nonlocal covered, blueprinted
        surface_id = item["surface_id"]
        summary = surface_index.get(surface_id)
        if summary:
            covered += 1
        hints = {
            "class_histogram": (summary or {}).get("class_histogram"),
            "content_descs": (summary or {}).get("content_descs"),
        }
        custom_reason = ""
        histogram = hints["class_histogram"]
        if isinstance(histogram, dict) and any(
            any(draw in str(cls) for draw in CUSTOM_DRAW_CLASSES) for cls in histogram
        ):
            matched = next(
                cls for cls in histogram
                if any(draw in str(cls) for draw in CUSTOM_DRAW_CLASSES)
            )
            custom_reason = (
                f"检测到自绘组件类 {matched}（系统组件无法表达，允许自定义绘制）"
            )
        structure = _android_structure_sentence(surface_id, summary)
        native_component = map_native_component(item["kind"], hints)
        matched_rule = _matched_rule(item["kind"], hints)
        if (
            item["kind"] == "page"
            and matched_rule == RULE_PAGE_TABS
            and tabs_owner is not None
            and surface_id != tabs_owner
        ):
            # 共享快照证据仲裁：Tab 特征词命中但唯一持有者是其它 page。
            matched_rule = RULE_PAGE_PLAIN
            native_component = map_native_component(item["kind"], {
                "class_histogram": None, "content_descs": None,
            })
            structure += (
                f"（Tab 特征词命中，但底栏 Tabs 唯一持有者为 {tabs_owner}"
                "——共享快照证据仲裁）"
            )
        item["android_structure"] = structure
        item["preserve"] = _preserve_contract(summary, global_palette)
        item["native_carrier"] = _native_carrier_note(route_or_mount)
        item["native_component"] = native_component
        item["matched_rule"] = matched_rule
        item["custom_allowed"] = "yes" if custom_reason else "no"
        item["reason"] = custom_reason
        blueprinted += 1

    for route in plan["routes"]:
        _annotate(route, "route")
    for modal in plan["modals"]:
        host = modal.get("host_surface_id")
        _annotate(modal, f"modal@{host}" if host else "modal@UNRESOLVED")
    for item in plan["passthrough"]:
        _annotate(item, "none")

    stats = plan.setdefault("stats", {})
    stats["ui_blueprint_surface_count"] = blueprinted
    stats["ui_blueprint_visual_memory_covered"] = covered
    summary_out = {
        "policy": "UI_FIDELITY=HIGH",
        "purpose": (
            "Android UI 在 HarmonyOS 上的原生表达决策（P3 冻结，"
            "Phase 4 按图施工，不临时发挥）"
        ),
        "mapping_rules": [
            "page+bottom-tabs -> Navigation+NavPathStack+Tabs(barPosition=End)+List+LazyForEach",
            "page+plain-content -> Navigation+NavPathStack+List/Scroll",
            "sheet -> bindSheet(detents MEDIUM/LARGE)",
            "dialog -> CustomDialog/bindMenu",
            "menu -> bindMenu",
            "container/component -> none (透传)",
        ],
        "tabs_owner_arbitration": {
            "rule": (
                "一个 Navigation 体系只有一个底栏 Tabs；多 page 共享同一"
                "快照证据时按 特征强度 > 主入口命名标记(HOME/MAIN/LAUNCHER)"
                " > nav 出度 > 字典序 仲裁唯一持有者"
            ),
            "tabs_owner_surface_id": tabs_owner,
            "tab_feature_page_ids": tab_feature_pages,
        },
        "custom_allowed_policy": (
            "默认 no；仅 class_histogram 出现自绘类（SurfaceView/TextureView/"
            "GLSurfaceView）判系统组件无法表达时 yes 并登记 reason"
        ),
        "visual_memory": visual_memory_source
        or {"available": visual_memory is not None},
        "stats": {
            "blueprinted_surface_count": blueprinted,
            "visual_memory_covered_surface_count": covered,
        },
    }
    plan["ui_blueprint"] = summary_out
    return summary_out


# ---------------------------------------------------------------------------
# 主题层（#77）：从 Phase 2 visual-memory.json（全局色板 + text_sizes 探测
# 记录）派生 Phase 3 设计 token —— AppTheme.ets 常量 + base/dark 两套
# color.json 资源 + surface-plan.json theme_tokens 摘要。
#
# 派生原则：token 值只从 visual-memory.global_palette 真实派生并逐一注明
# 来源 swatch 名；色板无对应数据（如 primary hex、字号、圆角）时退化为
# 平台默认/标准阶梯并注明，绝不发明视觉数据（不阻塞骨架生成）。
# ---------------------------------------------------------------------------

PHASE2_WORKSPACE_NAME = "phase-02-android-inventory"
THEME_FOUNDATION_FILE = "entry/src/main/ets/foundation/AppTheme.ets"
THEME_COLOR_BASE_FILE = "entry/src/main/resources/base/element/color.json"
THEME_COLOR_DARK_FILE = "entry/src/main/resources/dark/element/color.json"
THEME_MODE_PALETTE = "palette-derived"
THEME_MODE_DEFAULT = "platform-default"
THEME_DARK_SWATCH = "palette-dark-swatch"
THEME_DARK_INVERTED = "inverted-from-light"

# (token键, palette swatch 短名)：短名 = swatch name 最后一段（如
# GlasenseLightPalette.cardBackground -> cardBackground -> surface 槽）。
THEME_SWATCH_SLOTS: tuple[tuple[str, str], ...] = (
    ("background", "background"),
    ("pageBackground", "pageBackground"),
    ("surface", "cardBackground"),
    ("elevatedSurface", "elevatedCardBackground"),
    ("onBackground", "content"),
    ("onBackgroundVariant", "contentVariant"),
    ("onPrimary", "onPrimary"),
    ("primary", "primary"),
    ("scrim", "scrimNormal"),
)
# token键 -> 资源名（base/dark 同名，dark 目录同名覆盖即暗色限定资源）
THEME_RESOURCE_NAMES: dict[str, str] = {
    "background": "app_background",
    "pageBackground": "page_background",
    "surface": "surface",
    "elevatedSurface": "elevated_surface",
    "onBackground": "on_background",
    "onBackgroundVariant": "on_background_variant",
    "onPrimary": "on_primary",
    "primary": "app_primary",
    "scrim": "scrim",
}
# 平台默认退化值（visual-memory 缺失或该槽无 swatch 时；来源注明 platform-default）
THEME_PLATFORM_DEFAULTS: dict[str, str] = {
    "background": "#FFFFFF",
    "pageBackground": "#F1F3F5",
    "surface": "#FFFFFF",
    "elevatedSurface": "#FFFFFF",
    "onBackground": "#182431",
    "onBackgroundVariant": "#6B7280",
    "onPrimary": "#FFFFFF",
    "primary": "#007DFF",
    "scrim": "#66000000",
}
# 标准阶梯（visual-memory text_sizes.available=false 时使用）
THEME_TYPOGRAPHY_LADDER: dict[str, int] = {
    "display": 32, "title": 24, "subtitle": 20, "body": 16, "caption": 12,
}
THEME_SPACING_LADDER: dict[str, int] = {"xs": 4, "s": 8, "m": 12, "l": 16, "xl": 24}
THEME_RADIUS_LADDER: dict[str, int] = {"card": 12, "sheet": 16, "button": 20}


def _norm_hex(value: Any) -> str | None:
    """色值规范化为 #RRGGBB / #AARRGGBB 大写；非法输入返回 None。"""
    if not isinstance(value, str):
        return None
    text = value.strip()
    if not text.startswith("#"):
        text = "#" + text
    body = text[1:]
    if len(body) == 3 and all(ch in "0123456789abcdefABCDEF" for ch in body):
        body = "".join(ch * 2 for ch in body)
    if len(body) not in (6, 8) or not all(ch in "0123456789abcdefABCDEF" for ch in body):
        return None
    return "#" + body.upper()


def _invert_hex(hex_value: str) -> str:
    """明色反演为暗色（HSL 亮度 L -> 1-L，保色相与饱和度；保留 alpha 通道）。

    仅用于色板缺失 Dark swatch 时的 dark 资源退化（摘要注明
    inverted-from-light），不用于已有 palette-dark 数据的 token。
    """
    body = hex_value.lstrip("#")
    if len(body) == 8:
        # #AARRGGBB 惯例：前两位 alpha，后六位 RGB（如 #66000000 = 40% 黑）
        alpha, rgb = body[:2], body[2:]
    else:
        alpha, rgb = None, body
    r, g, b = (int(rgb[i:i + 2], 16) / 255.0 for i in (0, 2, 4))
    hue, light, sat = colorsys.rgb_to_hls(r, g, b)
    r2, g2, b2 = colorsys.hls_to_rgb(hue, 1.0 - light, sat)
    inverted = f"{round(r2 * 255):02X}{round(g2 * 255):02X}{round(b2 * 255):02X}"
    return f"#{alpha.upper()}{inverted}" if alpha else f"#{inverted}"


def _palette_index(
    global_palette: dict[str, Any],
) -> tuple[dict[str, str], dict[str, str], dict[str, str], dict[str, str]]:
    """PALETTE swatches -> (light hex 索引, dark hex 索引, light 全名, dark 全名)。

    短名 = name 最后一段；name 含 'Dark' 归 dark 组（GlasenseDarkPalette.*）。
    background_colors / theme_colors 列表并入同索引（去重，先到先得）。
    全名索引用于 token 来源标注（swatch 名保真）。
    """
    light: dict[str, str] = {}
    dark: dict[str, str] = {}
    light_names: dict[str, str] = {}
    dark_names: dict[str, str] = {}

    def _absorb(name: Any, hex_value: Any) -> None:
        normalized = _norm_hex(hex_value)
        if not isinstance(name, str) or normalized is None:
            return
        # 常规 palette 名带前缀（GlasenseLightPalette.background）；裸 token
        # 名（Blue500）无点号，以全名兼作短名收录（供渐变 stops 解析）。
        short = name.rsplit(".", 1)[-1] if "." in name else name
        target = dark if "Dark" in name else light
        names = dark_names if "Dark" in name else light_names
        if short not in target:
            target[short] = normalized
            names[short] = name

    for swatch in global_palette.get("swatches") or []:
        if isinstance(swatch, dict) and swatch.get("kind") == "PALETTE":
            _absorb(swatch.get("name"), swatch.get("hex"))
    for swatch in global_palette.get("background_colors") or []:
        if isinstance(swatch, dict):
            _absorb(swatch.get("name"), swatch.get("hex"))
    for swatch in global_palette.get("theme_colors") or []:
        if isinstance(swatch, dict):
            _absorb(swatch.get("name"), swatch.get("hex"))
    return light, dark, light_names, dark_names


def _derive_gradient(global_palette: dict[str, Any]) -> dict[str, Any] | None:
    """挑选代表渐变（多 stop 优先，candidate 顺序），保留 stops 原始顺序。

    stops 为源码 token 引用（如 Blue500）：仅当每个 token 都能在 PALETTE
    索引中解析出 hex 时输出 hex 数组，否则保真 token 名并标 resolved=false
    （Phase 4 视觉修复轮按 theme 源码解析补值，不在此发明色值）。
    """
    light, dark, _, _ = _palette_index(global_palette)
    candidates = [
        swatch for swatch in (global_palette.get("swatches") or [])
        if isinstance(swatch, dict) and swatch.get("kind") == "GRADIENT"
        and isinstance(swatch.get("tokens"), list) and swatch["tokens"]
    ]
    if not candidates:
        return None
    multi = [s for s in candidates if len(s["tokens"]) > 1]
    chosen = (multi or candidates)[0]
    stops = [str(token) for token in chosen["tokens"]]
    hexes: list[str | None] = []
    for token in stops:
        resolved = light.get(token) or dark.get(token)
        hexes.append(resolved)
    origin = chosen.get("origin") if isinstance(chosen.get("origin"), dict) else {}
    return {
        "source_swatch": str(chosen.get("candidate_id") or chosen.get("name") or "gradient"),
        "source_name": str(chosen.get("name") or ""),
        "origin_ref": (
            f"{origin.get('file', '?')}:{origin.get('line', '?')}" if origin else "n/a"
        ),
        "stops": stops,
        "resolved_to_hex": all(hex_value is not None for hex_value in hexes),
        "hexes": hexes if all(hex_value is not None for hex_value in hexes) else None,
    }


def _derive_theme_tokens(visual_memory: dict[str, Any] | None) -> dict[str, Any]:
    """visual-memory -> 主题 token 集（纯函数：确定性、无 IO、可单测）。

    返回：light/dark 色值 + 每槽 source（swatch 全名 / platform-default /
    inverted:<light 来源>）+ 渐变 + 字号阶梯来源；dark 缺失槽由明色反演
    （dark_mode 记录 inverted-from-light；primary 无 swatch 时保持平台
    默认主色，不计为反演）。
    """
    source_map: dict[str, str] = {}
    dark_source_map: dict[str, str] = {}
    light_values: dict[str, str] = {}
    dark_values: dict[str, str] = {}
    used_inversion = False
    palette = (
        visual_memory.get("global_palette")
        if isinstance(visual_memory, dict)
        and isinstance(visual_memory.get("global_palette"), dict)
        else None
    )
    light_index, dark_index, light_names, dark_names = _palette_index(palette or {})
    for token_key, swatch_short in THEME_SWATCH_SLOTS:
        if swatch_short in light_index:
            light_values[token_key] = light_index[swatch_short]
            source_map[token_key] = light_names[swatch_short]
        else:
            light_values[token_key] = THEME_PLATFORM_DEFAULTS[token_key]
            source_map[token_key] = "platform-default"
        if swatch_short in dark_index:
            dark_values[token_key] = dark_index[swatch_short]
            dark_source_map[token_key] = dark_names[swatch_short]
        elif token_key == "primary":
            # primary 槽两侧都可能无 swatch：保持平台默认主色（不做反演，
            # 品牌主色明暗一致；来源注明 platform-default）。
            dark_values[token_key] = THEME_PLATFORM_DEFAULTS[token_key]
            dark_source_map[token_key] = "platform-default"
        else:
            dark_values[token_key] = _invert_hex(light_values[token_key])
            dark_source_map[token_key] = f"inverted:{source_map[token_key]}"
            used_inversion = True
    if not palette:
        dark_mode = THEME_MODE_DEFAULT
    elif used_inversion:
        dark_mode = THEME_DARK_INVERTED
    else:
        dark_mode = THEME_DARK_SWATCH
    gradient = _derive_gradient(palette or {}) if palette else None
    text_sizes = (
        visual_memory.get("text_sizes")
        if isinstance(visual_memory, dict)
        and isinstance(visual_memory.get("text_sizes"), dict)
        else {}
    )
    sizes_data = text_sizes.get("sizes") if isinstance(text_sizes.get("sizes"), dict) else None
    typography: dict[str, int] = dict(THEME_TYPOGRAPHY_LADDER)
    typography_source = "platform-standard-ladder"
    if text_sizes.get("available") is True and sizes_data:
        for ladder_key in typography:
            value = sizes_data.get(ladder_key)
            if isinstance(value, (int, float)):
                typography[ladder_key] = int(value)
        typography_source = "visual-memory-text-sizes"
    return {
        "mode": THEME_MODE_PALETTE if palette else THEME_MODE_DEFAULT,
        "light": light_values,
        "dark": dark_values,
        "dark_mode": dark_mode,
        "source_map": source_map,
        "dark_source_map": dark_source_map,
        "gradient": gradient,
        "typography": typography,
        "typography_source": typography_source,
        "typography_note": str(text_sizes.get("note") or ""),
        "text_sizes_available": text_sizes.get("available") is True,
        "swatch_count": int(palette.get("swatch_count") or 0) if palette else 0,
    }


def _render_app_theme(tokens: dict[str, Any], meta: dict[str, Any]) -> str:
    """token 集 -> AppTheme.ets（确定性渲染；每 token 行尾注明来源）。"""
    light, dark = tokens["light"], tokens["dark"]
    source_map = tokens["source_map"]
    dark_source_map = tokens["dark_source_map"]
    gradient = tokens["gradient"]
    lines: list[str] = []
    lines.append(
        "// Design tokens generated deterministically by init_scaffold"
        " (emit_theme_layer) from the"
    )
    lines.append(f"// Phase 2 visual memory: {meta['visual_memory_path']}")
    if tokens["mode"] == THEME_MODE_PALETTE:
        lines.append(
            f"// Palette basis: global ({tokens['swatch_count']} swatches); every color"
            " token annotates its source"
        )
        lines.append("// swatch name inline. Slots without palette data fall back to")
        lines.append("// platform defaults and are annotated as platform-default.")
    else:
        lines.append(
            "// visual-memory.json was NOT available: all tokens fall back to platform"
        )
        lines.append("// defaults (annotated platform-default); the Phase 4 visual pass")
        lines.append("// may re-derive tokens once visual memory exists. Scaffold is not blocked.")
    if not tokens["text_sizes_available"]:
        lines.append("// Typography: visual-memory has no font-size data")
        lines.append(f"// (text_sizes.available=false: {tokens['typography_note'] or 'n/a'})")
        lines.append("// values follow the platform standard ladder in fp units.")
    else:
        lines.append("// Typography: derived from visual-memory text_sizes (fp units).")
    lines.append(
        "// Spacing/radius: platform standard ladders (uiautomator key_bounds carries"
    )
    lines.append(
        "// bounds only, no corner-radius attribute; radius values follow platform"
    )
    lines.append("// guidance scaled to key_bounds control sizes)."
    )
    lines.append("")
    lines.append("export class AppTheme {")
    lines.append("  // ---- colors (light + dark variants; sources annotated inline) ----")
    lines.append("  static readonly colors: Record<string, string> = {")
    for token_key, _ in THEME_SWATCH_SLOTS:
        lines.append(
            f"    {token_key}: '{light[token_key]}',  // {source_map[token_key]}"
        )
    for token_key, _ in THEME_SWATCH_SLOTS:
        lines.append(
            f"    {token_key}Dark: '{dark[token_key]}',  // {dark_source_map[token_key]}"
        )
    lines.append("  }")
    lines.append("")
    if gradient:
        lines.append("  // ---- gradients (stops order preserved from source) ----")
        lines.append(
            f"  // source swatch: {gradient['source_swatch']} ({gradient['source_name']})"
            f" @ {gradient['origin_ref']}"
        )
        if gradient["resolved_to_hex"]:
            stops_literal = ", ".join(f"'{value}'" for value in gradient["hexes"])
            lines.append(
                f"  static readonly gradients: Record<string, string[]> = {{ accent: [{stops_literal}] }}"
                "// hex stops resolved from palette"
            )
        else:
            stops_literal = ", ".join(f"'{token}'" for token in gradient["stops"])
            lines.append(
                f"  static readonly gradients: Record<string, string[]> = {{ accentTokens: [{stops_literal}] }}"
            )
            lines.append(
                "    // stops are source token references: visual-memory carries no token->hex"
            )
            lines.append(
                "    // resolution; Phase 4 visual pass resolves them via the Android theme source."
            )
    else:
        lines.append("  // ---- gradients (none in visual memory) ----")
        lines.append("  static readonly gradients: Record<string, string[]> = { accentTokens: [] }")
    lines.append("")
    lines.append("  // ---- typography ladder (fp) ----")
    lines.append("  static readonly typography: Record<string, number> = {")
    for ladder_key, value in tokens["typography"].items():
        lines.append(f"    {ladder_key}: {value},")
    lines.append("  }")
    lines.append("")
    lines.append("  // ---- spacing ladder (vp) ----")
    lines.append("  static readonly spacing: Record<string, number> = {")
    for ladder_key, value in THEME_SPACING_LADDER.items():
        lines.append(f"    {ladder_key}: {value},")
    lines.append("  }")
    lines.append("")
    lines.append("  // ---- radius ladder (vp) ----")
    lines.append("  static readonly radius: Record<string, number> = {")
    for ladder_key, value in THEME_RADIUS_LADDER.items():
        lines.append(f"    {ladder_key}: {value},")
    lines.append("  }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _render_color_resources(tokens: dict[str, Any]) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """token 集 -> (base 条目, dark 条目)（HarmonyOS element/color.json 结构）。"""
    base_entries = [
        {"name": THEME_RESOURCE_NAMES[key], "value": tokens["light"][key]}
        for key, _ in THEME_SWATCH_SLOTS
    ]
    dark_entries = [
        {"name": THEME_RESOURCE_NAMES[key], "value": tokens["dark"][key]}
        for key, _ in THEME_SWATCH_SLOTS
    ]
    return base_entries, dark_entries


def _locate_visual_memory(
    workspace: Path, input_lock: dict[str, Any]
) -> tuple[Path | None, list[str]]:
    """visual-memory.json 定位：input-lock inputs 推导优先，phase2 工作区次之。"""
    tried: list[str] = []
    candidates: list[Path] = []
    inputs = input_lock.get("inputs") if isinstance(input_lock.get("inputs"), dict) else {}
    feature_map_entry = inputs.get("feature_map") if isinstance(inputs.get("feature_map"), dict) else {}
    feature_map_path = str(feature_map_entry.get("path") or "")
    if feature_map_path:
        candidates.append(Path(feature_map_path).resolve().parent / "visual-memory.json")
    candidates.append(workspace.parent / PHASE2_WORKSPACE_NAME / "visual-memory.json")
    for candidate in candidates:
        tried.append(str(candidate))
        if candidate.is_file() and not candidate.is_symlink():
            return candidate, tried
    return None, tried


def emit_theme_layer(workspace: Path, input_lock: dict[str, Any]) -> dict[str, Any]:
    """主题层入口：派生 token 并写入骨架工程 + surface-plan 摘要（幂等可重放）。

    产物（相对 workspace/harmony-project）：
    - entry/src/main/ets/foundation/AppTheme.ets
    - entry/src/main/resources/{base,dark}/element/color.json
    surface-plan.json（存在且合法时）追加 theme_tokens 摘要。visual-memory
    缺失时全部退化为平台默认（mode=platform-default），不阻塞骨架。
    """
    workspace = Path(workspace)
    visual_memory_path, tried = _locate_visual_memory(workspace, input_lock)
    visual_memory: dict[str, Any] | None = None
    visual_memory_sha256: str | None = None
    if visual_memory_path is not None:
        try:
            loaded = load_json(visual_memory_path)
        except ValueError:
            loaded = None
        if isinstance(loaded, dict):
            visual_memory = loaded
            visual_memory_sha256 = sha256_file(visual_memory_path)
    tokens = _derive_theme_tokens(visual_memory)
    meta = {
        "visual_memory_path": (
            str(visual_memory_path) if visual_memory_path is not None
            else f"not found (tried: {', '.join(tried)})"
        ),
    }
    project_root = workspace / "harmony-project"
    base_entries, dark_entries = _render_color_resources(tokens)
    atomic_text(project_root / THEME_FOUNDATION_FILE, _render_app_theme(tokens, meta))
    atomic_json(project_root / THEME_COLOR_BASE_FILE, {"color": base_entries})
    atomic_json(project_root / THEME_COLOR_DARK_FILE, {"color": dark_entries})
    summary: dict[str, Any] = {
        "generated_by": "emit_theme_layer",
        "mode": tokens["mode"],
        "visual_memory": {
            "path": str(visual_memory_path) if visual_memory_path else None,
            "sha256": visual_memory_sha256,
            "available": visual_memory is not None,
        },
        "color_token_count": len(THEME_SWATCH_SLOTS) * 2,
        "resource_color_count": len(THEME_RESOURCE_NAMES),
        "dark_mode": tokens["dark_mode"],
        "gradient": tokens["gradient"],
        "typography": {
            "source": tokens["typography_source"],
            "ladder": tokens["typography"],
            "text_sizes_available": tokens["text_sizes_available"],
        },
        "spacing": {"source": "platform-standard-ladder", "ladder": THEME_SPACING_LADDER},
        "radius": {
            "source": "platform-guidance (key_bounds carries no corner-radius attribute)",
            "ladder": THEME_RADIUS_LADDER,
        },
        "files": {
            "app_theme": THEME_FOUNDATION_FILE,
            "color_base": THEME_COLOR_BASE_FILE,
            "color_dark": THEME_COLOR_DARK_FILE,
        },
        "source_map": tokens["source_map"],
    }
    plan_path = workspace / "surface-plan.json"
    if plan_path.is_file():
        try:
            plan = load_json(plan_path)
        except ValueError:
            plan = None
        if isinstance(plan, dict):
            plan["theme_tokens"] = summary
            atomic_json(plan_path, plan)
    return summary


def main_v3() -> int:
    """唯一主流程：feature-map 驱动的功能承载面骨架 + 数据层 interface-only 契约。

    （#50：旧 main_gmi / legacy work-order 消费链已删除，v3 单路径。）
    - 门禁前置只直读冻结 phase-2-closure.json 的 gate（不重算 ws 目录
      哈希 / 不消费 audit-replay、coverage-ledger、completeness 源文件）；
    - 不消费旧契约布局与 inventory.csv 26 列页面行；
    - input-lock 为 scaffold-v3 schema（三个语义输入 + surfaces +
      data_contracts + capability_seeds）。
    """
    parser = argparse.ArgumentParser(
        prog="init_scaffold.py",
        description=__doc__,
    )
    parser.add_argument("--run-dir", required=True)
    parser.add_argument("--work-order", required=True)
    parser.add_argument("--architecture-lead", required=True)
    parser.add_argument(
        "--dry-run", action="store_true",
        help="只计算并输出 input-lock + 骨架计划，不创建 Phase 3 工作区",
    )
    args = parser.parse_args()

    try:
        run_dir = canonical_input(args.run_dir, "Migration run")
        work_order_path = canonical_input(args.work_order, "Phase 3 work order")
    except ValueError as exc:
        parser.error(str(exc))
    if not run_dir.is_dir():
        parser.error(f"Migration run does not exist: {run_dir}")

    def fail(message: str) -> None:
        parser.error(f"[v3] {message}")

    # ---- gmi 冻结闭包门禁（直读冻结 JSON；退役源文件重算） ----
    closure_path = run_dir / "phase-2-closure.json"
    try:
        closure = require_object(load_json(closure_path), "phase-2-closure.json")
    except ValueError as exc:
        fail(str(exc))
        return 2
    if closure.get("generator") != "gmi_closure":
        fail("phase-2-closure.json is not a gmi closure")
    gate = require_object(closure.get("gate"), "gmi closure gate")
    if gate.get("unmapped") != 0 or gate.get("audit_discrepancy") != 0:
        fail(
            f"gmi closure gate is not clean: unmapped={gate.get('unmapped')} "
            f"audit_discrepancy={gate.get('audit_discrepancy')}"
        )

    # ---- run-manifest / scope / gate-report / 工单链（保留项） ----
    try:
        run_manifest = require_object(load_json(run_dir / "run-manifest.json"), "run-manifest.json")
        scope = require_object(load_json(run_dir / "controller" / "scope.json"), "controller scope")
        gate_report = require_object(
            load_json(run_dir / "controller" / "gate-report.json"), "controller gate"
        )
        work_order = require_object(load_json(work_order_path), "Phase 3 work order")
    except ValueError as exc:
        fail(str(exc))
        return 2
    if run_manifest.get("phase2_closure_gate") != gate:
        fail("run-manifest phase2_closure_gate differs from the frozen gmi closure")
    if gate_report.get("phase") != 2 or gate_report.get("verdict") != "PASS":
        fail("controller gate-report is not a Phase 2 PASS")
    if "gate" in gate_report and gate_report.get("gate") != gate:
        fail("controller gate-report gate differs from the frozen gmi closure")

    work_orders_root = (run_dir / "controller" / "work-orders").resolve()
    try:
        work_order_path.relative_to(work_orders_root)
    except ValueError:
        fail(f"Work order must be controller-owned below: {work_orders_root}")
        return 2
    migration_scope = scope.get("migration_scope", {})
    included = list(migration_scope.get("included_features", []))
    excluded = list(migration_scope.get("excluded_features", []))
    if not included:
        fail("Frozen included feature scope is empty")
        return 2
    try:
        ownership = validate_phase3_ownership(work_order, scope)
    except ValueError as exc:
        fail(str(exc))
        return 2
    if args.architecture_lead != ownership["architecture_lead_id"]:
        fail("--architecture-lead must equal the controller-assigned Phase 3 architecture lead")
    registry_matches = [
        row for row in read_csv(run_dir / "controller" / "work-order-registry.csv")
        if row.get("work_order_id") == work_order.get("work_order_id")
    ]
    registry_relative = work_order_path.relative_to(run_dir).as_posix()
    scope_sha256 = sha256_file(run_dir / "controller" / "scope.json")
    work_order_sha256 = sha256_file(work_order_path)
    gate_report_sha256 = sha256_file(run_dir / "controller" / "gate-report.json")
    if (
        work_order.get("phase") != 3
        or work_order.get("status") != "ISSUED"
        or work_order.get("run_id") != scope.get("run_id")
        or work_order.get("issued_by") != scope.get("ownership", {}).get("migration_controller_id")
        or work_order.get("required_skill") != "harmonyos-migration-scaffold"
        or work_order.get("included_features") != included
        or work_order.get("excluded_features") != excluded
        or work_order.get("phase2_gate_sha256") != gate_report_sha256
        or work_order.get("scope_sha256") != scope_sha256
        or len(registry_matches) != 1
        or registry_matches[0].get("phase") != "3"
        or registry_matches[0].get("relative_path") != registry_relative
        or registry_matches[0].get("scope_sha256") != scope_sha256
        or registry_matches[0].get("work_order_sha256") != work_order_sha256
        or registry_matches[0].get("status") != "ISSUED"
    ):
        fail("Phase 3 work order is not the exact controller-registered frozen order")
    for feature_id in included + excluded:
        try:
            validate_id(feature_id, "Feature-ID in controller scope")
        except ValueError as exc:
            fail(str(exc))
            return 2

    # ---- v3 语义输入（必需）：feature-map / navigation-relations / data-relations ----
    phase2 = run_dir / "phase-02-android-inventory"
    if phase2.is_symlink() or phase2.parent != run_dir or not phase2.is_dir():
        fail("Phase 2 workspace must be the canonical run-owned directory")
        return 2
    feature_map_path = phase2 / "feature-map.json"
    nav_path = phase2 / "candidates" / "navigation-relations.candidates.csv"
    data_relations_path = phase2 / "data-relations.csv"
    for label, path in (
        ("feature-map.json", feature_map_path),
        ("navigation-relations.candidates.csv", nav_path),
        ("data-relations.csv", data_relations_path),
    ):
        if not path.is_file():
            fail(f"Missing v3 semantic input ({label}): {path}")
            return 2
    try:
        feature_map = load_feature_map(feature_map_path)
    except ValueError as exc:
        fail(str(exc))
        return 2
    if sorted(feature_map["included"]) != sorted(included):
        fail("feature-map coverage differs from the frozen controller scope")
    try:
        navigation_relations = semantic_csv_rows(nav_path, "P2 navigation-relations candidates")
        # 批次 3（#86）：behavior-contracts.csv 作为 required_operations 的
        # BC 佐证来源（缺失不阻塞，操作集退化为静态基表/KV 缺省/directions）。
        behavior_contracts_path = phase2 / "behavior-contracts.csv"
        data_objects, data_stats = data_contracts.load_and_build(
            data_relations_path, behavior_contracts_path
        )
    except ValueError as exc:
        fail(str(exc))
        return 2
    plan = build_surface_plan(feature_map, navigation_relations)
    # ---- UI 蓝图层（批次 3 #86）：surface-plan 的 UI 原生化决策 ----
    # visual-memory 为权威结构证据源：存在则加载（坏 JSON 退化不阻塞，
    # 如实登记 unavailable），每 surface 冻结 native_component/preserve 等
    # 六字段，Phase 4 按图施工。
    visual_memory_path = phase2 / "visual-memory.json"
    visual_memory: dict[str, Any] | None = None
    visual_memory_source: dict[str, Any] = {
        "available": False,
        "path": str(visual_memory_path),
        "sha256": None,
        "note": "visual-memory.json not found; blueprint degrades to feature-map-only",
    }
    if visual_memory_path.is_file():
        try:
            loaded_vm = load_json(visual_memory_path)
        except ValueError:
            loaded_vm = None
        if isinstance(loaded_vm, dict):
            visual_memory = loaded_vm
            visual_memory_source = {
                "available": True,
                "path": str(visual_memory_path),
                "sha256": sha256_file(visual_memory_path),
                "surface_count": len(loaded_vm.get("surfaces") or []),
            }
        else:
            visual_memory_source["note"] = (
                "visual-memory.json is not a valid JSON object; "
                "blueprint degrades to feature-map-only"
            )
    ui_blueprint_summary = attach_ui_blueprint(plan, visual_memory, visual_memory_source)

    # ---- asset 链（保留：哈希链 + 生命周期；退役 inventory.csv 交叉） ----
    # v3 三态：完整旧链（asset-inventory + manifest + COMMITTED）→ 严格校验；
    # 完全缺失（新范式 Phase 2 未收集资产）→ assets=0 跳过；残缺 → 报错。
    asset_inventory_path = phase2 / "asset-inventory.csv"
    asset_package_path = phase2 / "asset-package"
    asset_chain_present = all(
        path.is_file()
        for path in (
            asset_inventory_path, asset_package_path / "manifest.sha256",
            asset_package_path / "COMMITTED",
        )
    )
    asset_package_files = (
        asset_package_path / "files"
        if (asset_package_path / "files").is_dir()
        else None
    )
    asset_package_has_files = bool(
        asset_package_files and any(asset_package_files.rglob("*"))
    )
    asset_registry_rows: list[dict[str, str]] = []
    if not asset_chain_present and asset_package_has_files:
        fail("Phase 2 asset package has files but lacks the committed manifest chain")
        return 2
    if asset_chain_present and asset_package_has_files:
        if csv_fieldnames(asset_inventory_path) != ASSET_INVENTORY_FIELDS:
            fail("Phase 2 asset-inventory.csv header differs from the handoff contract")
            return 2
        package = asset_package_path
        manifest_path = package / "manifest.sha256"
        committed_path = package / "COMMITTED"
        if committed_path.read_text(encoding="utf-8") != sha256_file(manifest_path) + "\n":
            fail("Phase 2 asset COMMITTED marker differs from manifest.sha256")
        manifest_entries: dict[str, str] = {}
        for number, line in enumerate(manifest_path.read_text(encoding="utf-8").splitlines(), 1):
            if "  " not in line:
                fail(f"Malformed Phase 2 asset manifest line {number}")
                return 2
            digest, relative = line.split("  ", 1)
            if not SHA256_RE.fullmatch(digest) or relative in manifest_entries:
                fail(f"Unsafe or duplicate Phase 2 asset manifest entry: {relative!r}")
                return 2
            manifest_entries[relative] = digest
        for row in read_csv(asset_inventory_path):
            asset_id = row.get("asset_id", "")
            archive = row.get("archive_path", "")
            digest = row.get("sha256", "")
            artifact = package / archive.removeprefix("asset-package/")
            if (
                manifest_entries.get(archive.removeprefix("asset-package/")) != digest
                or not artifact.is_file()
                or sha256_file(artifact) != digest
            ):
                fail(f"Phase 2 asset hash chain differs: {asset_id}")
                return 2
            asset_registry_rows.append(
                {
                    "asset_id": asset_id, "phase2_archive_path": archive,
                    "asset_sha256": digest, "asset_type": row.get("asset_type", ""),
                    "feature_ids": row.get("feature_ids", ""), "page_ids": row.get("page_ids", ""),
                    "state_ids": row.get("state_ids", ""),
                    "target_module_id": "", "target_path": "", "target_symbol": "",
                    "planned_mode": "", "decision": "", "created_by": "",
                    "status": "NOT_STARTED", "notes": row.get("notes", ""),
                }
            )
        asset_registry_rows.sort(key=lambda row: row["asset_id"])

    # ---- 模板工程参数 ----
    android_scope = scope.get("android", {}) if isinstance(scope.get("android"), dict) else {}
    bundle_name = str(android_scope.get("application_id", "")).strip()
    if not re.fullmatch(r"[a-z][a-z0-9]*(?:\.[a-z][a-z0-9]*)+", bundle_name):
        fail("Frozen Android application_id cannot seed a valid HarmonyOS bundle name")
        return 2
    app_name = str(scope.get("project_name") or scope.get("project_id") or bundle_name).strip()
    template_replacements = {
        "__BUNDLE_NAME__": bundle_name,
        "__APP_NAME__": json.dumps(app_name, ensure_ascii=False)[1:-1],
        "__VENDOR__": "migration",
        "__LOG_TAG__": re.sub(r"[^A-Za-z0-9_.-]", "", app_name)[:31] or "MigrationScaffold",
    }

    # ---- input-lock v3 ----
    initialized_at = utc_now()
    # #48 裁定：inputs.* 的 path/snapshot_path 全部输出绝对规范路径
    # （phase_dir 提前定义，供快照落点在 input-lock 内直接引用）。
    phase_dir = run_dir / PHASE_NAME
    inputs_dir = phase_dir / "inputs"
    data_source = {
        # #48 裁定：与 feature_map/navigation_relations 一致输出绝对规范路径。
        "path": str(data_relations_path.resolve()),
        "sha256": data_stats["sha256"],
        "row_count": data_stats["row_count"],
    }
    data_contract_entries: list[dict[str, Any]] = []
    capability_seeds: list[dict[str, Any]] = []
    for object_id in sorted(data_objects):
        entry = data_objects[object_id]
        relative = f"{object_id}.json"
        # #48 裁定：data_contracts 数组按 (feature, object) 组合展开——
        # 每组合含 E 的消费键 {feature_id（单值）, data_object（=raw_name
        # 语义名）, interface（=repository_symbol）}，并保留聚合附加列；
        # 孤儿对象（feature_ids 为空）无组合，不进展开数组（能力种子仍
        # 如实聚合，语义对象集不含孤儿行）。
        for feature_id in sorted(entry["feature_ids"]):
            data_contract_entries.append(
                {
                    "feature_id": feature_id,
                    "data_object": entry["raw_name"],
                    "interface": entry["repository_symbol"],
                    "object_id": object_id,
                    "raw_name": entry["raw_name"],
                    "repository_symbol": entry["repository_symbol"],
                    "directions": sorted(entry["directions"]),
                    "android_persistence": sorted(entry["android_persistence"]),
                    "feature_ids": sorted(entry["feature_ids"]),
                    "contract_file": f"data-contracts/{relative}",
                }
            )
        capability_seeds.append(
            data_contracts.capability_seed(entry, f"data-contracts/{relative}")
        )
    input_lock: dict[str, Any] = {
        "schema_version": "scaffold-v3",
        "paradigm": V3_PARADIGM,
        "run_id": run_manifest.get("run_id"),
        "project_id": run_manifest.get("project_id"),
        "locked_at": initialized_at,
        "locked_by": args.architecture_lead,
        "work_order_id": work_order.get("work_order_id"),
        "work_order_sha256": work_order_sha256,
        "ownership": ownership,
        "gate_mode": "feature-semantic",
        "inputs": {
            "feature_map": {
                "path": str(feature_map_path.resolve()),
                "sha256": sha256_file(feature_map_path),
                "feature_count": feature_map["feature_count"],
                "surface_count": feature_map["surface_count"],
            },
            "navigation_relations": {
                "path": str(nav_path.resolve()),
                "sha256": sha256_file(nav_path),
                "row_count": len(navigation_relations),
            },
            "data_relations": {
                **data_source,
                "rows_skipped_empty_object": data_stats["rows_skipped_empty_object"],
                "semantic_object_count": data_stats["object_count"],
            },
            "scope": input_record(
                run_dir / "controller" / "scope.json",
                inputs_dir / "controller-scope.json",
            ),
            "phase2_gate": {
                "path": str((inputs_dir / "phase-02-gate-report.json").resolve()),
                "sha256": gate_report_sha256,
            },
            "phase2_closure": input_record(
                closure_path, inputs_dir / "phase-02-gmi-closure.json"
            ),
            "phase3_work_order": {
                "path": str((inputs_dir / "phase-03-work-order.json").resolve()),
                "sha256": work_order_sha256,
            },
        },
        "included_feature_ids": sorted(included),
        "excluded_feature_ids": sorted(excluded),
        "surfaces": surface_lock_entries(plan),
        "surface_plan_stats": plan["stats"],
        "data_contracts": data_contract_entries,
        "capability_seeds": capability_seeds,
        "obligations": [],
        "obligations_note": "v3 does not consume probe/audit obligations chains",
        "retired_inputs_note": V3_RETIREMENT_NOTE,
        "arkui_template": {
            "template_id": "ARKUI-STAGE-TEMPLATE-V1",
            "manifest_path": "inputs/arkui-stage-template.manifest.sha256",
            "file_count": len(template_files(ARKUI_TEMPLATE)),
        },
    }

    # ---- dry-run：输出计划即止，不落盘 ----
    if args.dry_run:
        print(json.dumps({
            "dry_run": True,
            "paradigm": V3_PARADIGM,
            "workspace_would_be": str(run_dir / PHASE_NAME),
            "input_lock": input_lock,
            "surface_plan": plan,
            "data_contracts_index": data_contract_entries,
            "assets": len(asset_registry_rows),
        }, ensure_ascii=False, indent=2))
        return 0

    # ---- 工作区生成 ----
    # phase_dir/inputs_dir 已在 input-lock 构造段提前定义（#48 裁定）。
    if phase_dir.exists():
        fail(f"Phase 3 workspace already exists; overwrite is prohibited: {phase_dir}")
        return 2
    input_snapshots = {
        "controller_scope": inputs_dir / "controller-scope.json",
        "phase2_gate": inputs_dir / "phase-02-gate-report.json",
        "phase2_gmi_closure": inputs_dir / "phase-02-gmi-closure.json",
        "phase3_work_order": inputs_dir / "phase-03-work-order.json",
        "feature_map": inputs_dir / "phase-02-feature-map.json",
        "navigation_relations": inputs_dir / "phase-02-navigation-relations.csv",
        "data_relations": inputs_dir / "phase-02-data-relations.csv",
        "arkui_template_manifest": inputs_dir / "arkui-stage-template.manifest.sha256",
    }
    if asset_chain_present and asset_package_has_files:
        input_snapshots["phase2_asset_inventory"] = inputs_dir / "phase-02-asset-inventory.csv"
    copy_sources = {
        "controller_scope": run_dir / "controller" / "scope.json",
        "phase2_gate": run_dir / "controller" / "gate-report.json",
        "phase2_gmi_closure": closure_path,
        "phase3_work_order": work_order_path,
        "feature_map": feature_map_path,
        "navigation_relations": nav_path,
        "data_relations": data_relations_path,
    }
    if asset_chain_present and asset_package_has_files:
        copy_sources["phase2_asset_inventory"] = asset_inventory_path

    architecture_rows: list[dict[str, str]] = []
    for surface in input_lock["surfaces"]:
        is_route = surface["route_or_mount"] == "route"
        is_modal = surface["route_or_mount"].startswith("modal@")
        architecture_rows.append(
            {
                "source_row_key": f"SURFACE:{surface['id']}",
                "inventory_id": "", "feature_id": surface["feature_id"],
                "page_id": surface["id"], "state_id": "", "env_id": "", "evidence_id": "",
                "mapping_type": "ROUTE" if is_route else ("MODAL" if is_modal else "PASSTHROUGH"),
                "harmony_module_id": "",
                "route_id": surface["id"] if is_route else "",
                "surface_shell_id": surface["shell_symbol"] or "" if is_modal else "",
                # #48 裁定：page_shell_id 输出大写 ID（PSHELL-<SURFACE-ID> 形态，
                # 如 ShellPageLogin → PSHELL-PAGE-LOGIN）；shell_file 与组件符号
                # （shell_symbol/surface_shell_id）保持驼峰。
                "page_shell_id": f"PSHELL-{surface['id']}" if is_route else "",
                "shell_file": surface["shell_file"] or "",
                "screenshot_ids": "", "verification_id": "", "mapped_by": "",
                "mapping_status": "NOT_STARTED",
                "notes": (
                    f"kind={surface['kind']};mount={surface['route_or_mount']}"
                    f";host_source={surface['mount_host_source'] or 'n/a'}"
                ),
            }
        )
    migration_rows = [
        {
            "source_kind": "FEATURE", "source_key": feature["feature_id"],
            "feature_id": feature["feature_id"], "page_id": "", "target_id": "",
            "status": "NOT_STARTED",
            "updated_by": ownership["architecture_lead_id"],
            "updated_at": initialized_at,
            "notes": f"surfaces={len(feature['surfaces'])}",
        }
        for feature in sorted(feature_map["features"], key=lambda f: f["feature_id"])
    ]
    capability_rows = [
        {
            "capability_requirement_id": requirement_id(
                ";".join(seed["feature_ids"]) or "NONE", "DATA_OBJECT", seed["contract_file"]
            ),
            "source_kind": "DATA_OBJECT",
            "source_feature_id": ";".join(seed["feature_ids"]),
            "source_requirement_ref": ";".join(seed["directions"]),
            "source_inventory_row_keys": "",
            "capability_contract_id": seed["capability_id"],
            "harmony_module_id": "", "contract_kind": seed["kind"],
            "contract_file": seed["contract_file"],
            "contract_symbol": seed["repository_symbol"],
            "created_by": ownership["capability_contract_agent_id"],
            "status": "NOT_STARTED",
            "notes": "v3 data-contract seed (interface-only; physical store free)",
        }
        for seed in capability_seeds
    ]

    with tempfile.TemporaryDirectory(prefix=f".{PHASE_NAME}-", dir=run_dir) as temp_name:
        temp_dir = Path(temp_name)
        for name in ("inputs", "environments", "verification", "gate-reports"):
            (temp_dir / name).mkdir()
        for key, source in copy_sources.items():
            relative = input_snapshots[key].relative_to(phase_dir)
            shutil.copyfile(source, temp_dir / relative)
        template_manifest_snapshot = temp_dir / input_snapshots["arkui_template_manifest"].relative_to(phase_dir)
        atomic_text(template_manifest_snapshot, template_manifest(ARKUI_TEMPLATE))
        project_generation = create_arkui_project(
            ARKUI_TEMPLATE, temp_dir / "harmony-project", template_replacements
        )
        actual_template_manifest_sha256 = sha256_file(template_manifest_snapshot)
        input_lock["arkui_template"]["manifest_sha256"] = actual_template_manifest_sha256
        project_generation["template_manifest_sha256"] = actual_template_manifest_sha256
        atomic_json(temp_dir / "template-generation.json", project_generation)

        project_root = temp_dir / "harmony-project"
        for route in plan["routes"]:
            shell_target = project_root / route["shell_file"]
            shell_target.parent.mkdir(parents=True, exist_ok=True)
            atomic_text(
                shell_target,
                render_page_shell(route["surface_id"], route["shell_symbol"], [route["feature_id"]]),
            )
        for modal in plan["modals"]:
            modal_target = project_root / modal["shell_file"]
            modal_target.parent.mkdir(parents=True, exist_ok=True)
            atomic_text(
                modal_target,
                render_modal_shell(
                    modal["surface_id"], modal["shell_symbol"],
                    modal["kind"], modal["host_surface_id"],
                ),
            )
        atomic_json(temp_dir / "surface-plan.json", {**plan, "generated_at": initialized_at})
        # 主题层（#77）：surface-plan 写入后派生（函数自读自改 surface-plan
        # 追加 theme_tokens 摘要；visual-memory 缺失时退化为平台默认不阻塞）。
        theme_summary = emit_theme_layer(temp_dir, input_lock)
        contracts_written = data_contracts.write_contracts(
            temp_dir / "data-contracts", data_objects, initialized_at, data_source
        )
        # 收敛式重构批次 2（#85）：DebugSemanticProbe 独立探针生成钩子——
        # data 断言的数据出口由冻结探针承载（替代应用侧自报 replay-data.
        # json）；probe_sha256 记入 input_lock，Phase 4 工单携带 expected
        # hash，Gate 4 校验 P4 实施者未篡改探针本体。
        probe_written = data_contracts.write_semantic_probe(
            project_root, data_objects
        )
        input_lock["semantic_probe"] = {
            "probe_relative_path": probe_written["probe_relative_path"],
            "probe_sha256": probe_written["probe_sha256"],
            "registry_relative_path": probe_written["registry_relative_path"],
            "registry_sha256": probe_written["registry_sha256"],
            "probe_keys": probe_written["probe_keys"],
            "snapshot_filename": data_contracts.PROBE_SNAPSHOT_FILENAME,
            "hilog_tag": data_contracts.PROBE_HILOG_TAG,
        }
        atomic_json(temp_dir / "stage-03-input-lock.json", input_lock)

        copy_template_csv(temp_dir, "module-registry.template.csv", "module-registry.csv")
        copy_template_csv(temp_dir, "route-registry.template.csv", "route-registry.csv")
        copy_template_csv(temp_dir, "surface-registry.template.csv", "surface-registry.csv")
        copy_template_csv(temp_dir, "public-ui-registry.template.csv", "public-ui-registry.csv")
        copy_template_csv(temp_dir, "architecture-decisions.template.csv", "architecture-decisions.csv")
        copy_template_csv(temp_dir, "rework-tickets.template.csv", "rework-tickets.csv")
        shutil.copyfile(ASSETS / "dependency-policy.template.json", temp_dir / "dependency-policy.json")
        shutil.copyfile(ASSETS / "henv-registry.template.csv", temp_dir / "environments" / "henv-registry.csv")
        write_csv(
            temp_dir / "architecture-map.csv",
            csv_fieldnames(ASSETS / "architecture-map.template.csv"), architecture_rows,
        )
        write_csv(
            temp_dir / "capability-contracts.csv",
            csv_fieldnames(ASSETS / "capability-contracts.template.csv"), capability_rows,
        )
        write_csv(
            temp_dir / "migration-status.csv",
            csv_fieldnames(ASSETS / "migration-status.template.csv"), migration_rows,
        )
        write_csv(
            temp_dir / "asset-registry.csv",
            csv_fieldnames(ASSETS / "asset-registry.template.csv"), asset_registry_rows,
        )
        atomic_json(
            temp_dir / "phase-manifest.json",
            {
                "run_id": run_manifest.get("run_id"), "project_id": run_manifest.get("project_id"),
                "phase": 3, "status": "IN_PROGRESS", "initialized_at": initialized_at,
                "paradigm": V3_PARADIGM,
                "architecture_lead": ownership["architecture_lead_id"],
                "ownership": ownership, "work_order_id": work_order.get("work_order_id"),
                "work_order_sha256": work_order_sha256,
                "gate_mode": "feature-semantic",
                "phase2_input_locked": True, "business_implementation_allowed": False,
                "gui_only_evidence_allowed": False, "mp4_required": False,
                "template_id": project_generation["template_id"],
                "template_manifest_sha256": project_generation["template_manifest_sha256"],
                "template_generation_sha256": sha256_file(temp_dir / "template-generation.json"),
            },
        )
        atomic_json(
            temp_dir / "build-report.json",
            {"status": "NOT_RUN", "verification_id": None, "updated_at": initialized_at},
        )
        atomic_json(
            temp_dir / "stage-03-gate-report.json",
            {"phase": 3, "verdict": "NOT_RUN", "reviewer_role": "architecture-acceptance-agent"},
        )
        temp_dir.rename(phase_dir)

    print(json.dumps({
        "paradigm": V3_PARADIGM,
        "gate_mode": "feature-semantic",
        "workspace": str(phase_dir), "work_order_id": work_order.get("work_order_id"),
        "features": feature_map["feature_count"],
        "surfaces": plan["stats"]["surface_count"],
        "routes": plan["stats"]["route_count"],
        "modals": plan["stats"]["modal_count"],
        "passthrough": plan["stats"]["passthrough_count"],
        "nav_edges_kept": plan["stats"]["nav_edge_kept"],
        "nav_pages_skipped": plan["stats"]["nav_pages_skipped"],
        "data_contracts": contracts_written["object_count"],
        "capability_seeds": len(capability_seeds),
        "assets": len(asset_registry_rows),
        "template_files": project_generation["generated_file_count"],
        "harmony_project": str(phase_dir / "harmony-project"),
        "theme_mode": theme_summary["mode"],
        "theme_color_tokens": theme_summary["color_token_count"],
        "ui_blueprint_surfaces": ui_blueprint_summary["stats"]["blueprinted_surface_count"],
        "ui_blueprint_visual_memory_covered": (
            ui_blueprint_summary["stats"]["visual_memory_covered_surface_count"]
        ),
    }, ensure_ascii=False))
    return 0




if __name__ == "__main__":
    # v3 单路径入口（#50）：旧 main_gmi / legacy 分发已删除。
    raise SystemExit(main_v3())
